# Generated by Django 3.1.6 on 2021-02-17 15:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rekening',
            name='no_rekening',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='rekening',
            name='saldo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Riwayat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penerima', models.CharField(max_length=16)),
                ('jumlah', models.PositiveIntegerField()),
                ('tanggal_transaksi', models.DateField(auto_now_add=True)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kirim', to='main.rekening')),
            ],
        ),
    ]
