# Generated by Django 3.1.6 on 2021-02-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210217_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat',
            name='tanggal_transaksi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
