# Generated by Django 3.1.6 on 2021-02-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riwayat',
            name='tanggal_transaksi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
